language: ruby
cache: bundler
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
env:
  global:
  - AWS_REGION=ap-southeast-1
  - CC_TEST_REPORTER_ID=9962bc6b09c6056784addb3115813b01b9a7ee03e409bc2c633cb211d07f3408
  # AWS Credentials
  - secure: Q45kN84Iw57MfH3oOMDjCdZIJWdvBxIqOfWUyN1kGB9Y613ZdY429eLBHUkZcScrVO/Rj6m8Fm8eH8ZbgSroWEd8pCr7ELYYxI/wSp6BxAXtsoJQk0h5GolaMmAuRGFCbwe1zJuWcFXg2oh5rH92P4HunauWYmizJbztx83+Vmp051NSDCYRCVZHMCuwM6c65CMryRgq1+ZlUMQa2oJ8G3BC2VDwkteVoyfjhKL/IsIpoutulze63wc6jneMFXVHY7Mwk7pgMg7jYECnZwhUpOgQ3ZOwhXys82vOTkav7IbRvsxoeVtGuvgmKvcPckYORmIJrbOdKBY3x7bO7JCsUnczKGqPh1xEBsevsXbxP1/HPbF0yZocNGN3JTWWAHrGVN00dvPn1tUW1uogSO/H35fFCPfwB5ilgfyoUxXXMRqHvjVV0jG4wGTsMDecF/w8GJrGZXuS4Ql2THjjmKgvPSvITdjJqOn3Ryb/mEwL1IkGNG4TJF86Oi3wuQvF8tPX6vaS5ft4zae310ixDDEFsnD5VV+qWgA6UBkoCNjo+0YZwdLLCgOBkz/b68bw7YM4dzK3Py6sbbbhBIJ0t1QI8wuT0/FFP6OsDbkawwO1wxduRausTlLjEgECll4pipWmf1Q54Q1CpQ0R68mUeatdkks/LwBKBCTENu9DAWDjnRE=
  # Docker Credentials
  - secure: NRLY7D93Sf8NHDGogA3Y06WBU08gEVHc52zsRIXVXRkyU2zYJMaDvGJvshxupjFkSRvT+23HlzVxfxU0rFldv5SugBIZ3XsCiHr/RlHuKGX2YYxb/qImoXpmmNe/ZEJLb0IElmGSHdwfN7aoDF/Z6lzKC89gXbK4QQphsQunnzgFiN9UCLa1IYPlQMyfhhILGbDDzBg4CKOuEehw2KVg2NjcYV9SlThBesVfdjtQV6P3QxX1wO77FDlF+q/F36/Ox/UKQJe0PAGmeuS3Bu9JQQcNGg8lQf7BMeAFiY/JOQx7ViFpbahMovEiuNVgV3WmpqJM6Q/nW2btfcJz7AtthcDx0lmG5+ZTsV/5R1p+5+z/giHplERT6QKpysywVo5vJ5ky05DHxU+8CcAOqozE8ljsbImvkpFVfmbFPuyFWb+pDGpl0Fv2BQu0qCwke0jwBjcBt8kOl2WuxhRhnD/py11fyC2ysE0ncd5SCY9GqLd/++7vrOMUvncY92R9rw14JBFRNe4pz/HfNuMb+Vt48QAQhtMxEiW/gaipVMN97LqfypC0uY6laNvVFO9RpNgkSwuVWARKFW7MkCl7r7HWVeTYQh3dSJoRMKN8C8jx1ZmFjXbrrMyZUAwCkjJycSatP/hukWsiGe6oIwrjb7CazxWBVvtmNMSkUHCMOMN5/zg=
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- gem install bundler
before_script:
- "./cc-test-reporter before-build"
after_success:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t pincambodia/somleng-adhearsion:latest "https://github.com/$TRAVIS_REPO_SLUG.git#$TRAVIS_BRANCH"
- docker push pincambodia/somleng-adhearsion
deploy:
- provider: elasticbeanstalk
  app: somleng-adhearsion
  env: somleng-adhearsion-webserver
  region: ap-southeast-1
  bucket_name: deploy.ews1294.info
  on:
    branch: master
