language: ruby
env:
  - START_SIMPLECOV=1
addons:
  code_climate:
    repo_token:
      secure: "riZtfOmLGpxlzZ9FBIpyJ6yVVznEeiRdRilUIF3SpY9Hq0ZiWlpklQZKM5piw6XI2VKfz/b59Nwc2fFFZfNKD2iHZAc546T6sVo07cGiZ5Rvz6DZA/11X2fQ90N3bjJs+vOTE9pAdtIqIqYdV7JtDVsDdcaU3R2Xhct4WmWKG94SMDKsPr74LDtZX8DfhZumwYWCEwpRzs4HSZ61/2+maxZqiRY4f3X47K2xnhBL53EE+mqyTxc+N7HowWrYBQlpOpHscBXwnHb6hnO63lC4FIa0M1ZXUKAY707Ixfv+cgvZq3Spjsp6KCAYIqa0EFa3Di21vxdya8S78Zr7OzGzswLBwDJ+rBy0jOEpleIcfC5OakLJw4mfog4jsOpNcDTHH/2yvYCw9iIFXkfU6ctOzXX6MyljtTJ7rKgnotOoa4zTxzcCqUcOALMQT5qaoxfj6VHu88epoJT8b09YVdwnz7w2rrvu5REF5XURWvoKuyA6WqPSH21R9WA9+Ec3zqdoJ5o0HRio2F4JYI/dxf7cLK53WzW7YhopuVdkzoCVY1H17NcAklDR7Lr8vxd0RhFT93w/ofWs+D/TAxmaJi7M/NSIvwKfeFRfhjb3NRort8Iv+QE/2zEovGGhahemTbUcJ+hRmgPN3+mYQUf0Q4AS60G4tecQBFTVFGS2/7Ky9pk="
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "ds7G9QYKTRufksa2Dq6IrnsqzR6kVV+2+xNAi4QoaHf9te8boemJXIzdcgrLk03LmmFJ9s/uCqQcAu3lOCfvpHq5rCveOiNsf++KdKw1JWXomV9KqSnT1PUWUklUBzWMTnf/aNg1F7XPJAMgIGdu39xiLVuw7EM1ROWbswW6pr7eYVhtIHJHNCFoGicvT9tfO9kSnF1cfrK0QB03xWqbpaaFsZc7Lm4t98TzRg7kyPoSgrFgQwmZ6bt/mt7oKlay+HzOnZ6L1oy0QZFTd7IrcfopuuJa8kcYb0RkOviS5xcimjy3Tiewi7FDsecSbfLl8Q4Emd2iu17zK4+kwZLzznuPTot+szcvkLu5n7K7FTfcy2Ls5C+g+nNWuxeXnEmkRBHvbKLmwSZyb528HZnE1gbEknaeos+FZBkXkZ5CwtEgYfpimn2X0mpC/32i8k/J07II2aEHA7d7tVUYf0ghQeBtFsYmkhBxUW1WQSLfN4a+lXZuXKNafqpPlPQCpBPzL6SDyYkIbNawS233jqOTp0Xjt4eChqB03UBrdY0YQZU/LhDeHy50QBhH3WwgRZBtwrrNLu9GJ9qlvT/O41qvZ669mrCYPLr7N6O738Y8xHdeHj8yYzzWWqT7q91bz5hH8PhBeDbOBa+Q9+/IDHK0j5alyLuwFuFCjR02axjXBaU="
    secret-access-key:
      secure: "HS9vs2KeBNoXzJ0rS65nW0XGr1CaktJpZs51gL4kb5MHNfuqDSFftxkMQqBe4bKp1ToS3RN8jSkr4SigcTSW0VQyEZiV1x53uFUW1jIa0OotgUkfkYKLxKv8GGp4sk+17OT+sHlyY/bZOUAFjbIX4e5fI6l9MXCE2IZ/2UAoqBOsZrEtukPL7NuRpEL2AgRpO+tNM23yUmXuBFDRfu+RQ7icFPkyIRNZO9i0MwkoV9VBDj7cR1jm1dBNrZqjQFzO2swPrL+dktpYwFZiKGGQW2td563y/JidUrOnuroAIHtC4poY3F9a0Pkut+b0kYiv9S0VBHYH2Z0rlHV2uieYB9RlqCEdxVW+NVoSvrPHXnDG1YEJZM1+6a6T0nr0rv+9W7JEKvUTTmZS1WNUmvUK5PoJO+4CynqcPQUMaQ3b8kIQWSBVj7yLnKlSApQpm/exyJUTCDWJBhuUiHAsCFG8QR84gIbyto50k298EkpunfThnj2NpQk8NHIDnfpwdshjWXhvf/1eTBmNd10GZoSTwAI+g01dhdQ8SF3dDDY0sdWCmzxNvss9gZ6C+9TABzfUbbRF9PHixbu4I616ihIQ+saO5Su6zk30A5rNSnaKlX/CBeld/S418RNU8lEMGetIdgMTx7PGhfcEBCr2iM2iItE4X6xEWTtSHAN5UAfD9jI="
    region: ap-southeast-1
    app: somleng
    env: somleng-production
    bucket_name: pin-somlengci
    on:
      repo: somleng/somleng
      branch: somleng.ews1294.info
      condition: $DOCKER = 1
