language: ruby
cache: bundler
addons:
env:
  global:
    - AWS_REGION=ap-southeast-1
    - CC_TEST_REPORTER_ID=dda6e39fff92f03327b728944253d3a58162a83e69a45f10918750786309a26a
    - CODECOV_TOKEN=cbfe3a70-5a7b-49c6-87d9-a955ec96900e
    - secure: "GIqHMg6hmvihUtF4/V5+id7zC/mwPyROquQUeBOEnwGYyFE7oKy6dlaLIU+iA4IADW8QeZC2C8z8faKo5GmLgWbV7macdbcqZHpaVYa8zjncuWRcYgV2UJa7rT9RrcNxxELCK9I8A3VDmyzs2VMbcelK8l0o1cR8/wL5mKY5Xbu4ihIVRJAzdWfEZkVUaPmLKU9Aw4M4wwSrJvKt9Yq+stDFMYDp7fCWYALVxDcAFzcHNFMk73Gmu42N2felbARpWNHnOh8fvK1ijszWvzMzv7/jq651CJ/dWzjxeVYARF4oycbFdMCm6f9z0LDf/9MKPX0aanWpqQVvBy1hzLTqfJP0N3EEj+3BycU1leK8xiXUE1tmXcHHRAvN9aNcH9Ip5ijP9L4JTGIC4FzUWDCc3UhRgS8y4WNZld48Kj/vHVF0mYQd5gCGDW+4PIFFqUh1sK3nbuC7AhtsjN2eITpg6IoWeTvYoWjFqK227SHErC+ALVI4mlseAhAnGQvevZ1BldjnVZfJMFIDGmh6/BMHZNfAt1Fq1r6+KIq7t6sRUGYIjUNRywvlxU+QEzAQNt3KmNykbb/gYKi/NtQXm7EXnR2m3vsfawNNf8XQxF9evvVMWbuIcRaODL/fY76b+tAAO32O3jlrt2dDhCYQ8r7to9bzPXEgzqzTsQXDxHo6XeY="
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - gem install bundler
before_script:
  - ./cc-test-reporter before-build
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  - provider: elasticbeanstalk
    region: ap-southeast-1
    app: somleng-adhearsion
    env: somleng-adhearsion-webserver
    bucket_name: deploy.unicef.io
    on:
      repo: somleng/somleng-adhearsion
      branch: somleng.unicef.io
