language: ruby
deploy:
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "ds7G9QYKTRufksa2Dq6IrnsqzR6kVV+2+xNAi4QoaHf9te8boemJXIzdcgrLk03LmmFJ9s/uCqQcAu3lOCfvpHq5rCveOiNsf++KdKw1JWXomV9KqSnT1PUWUklUBzWMTnf/aNg1F7XPJAMgIGdu39xiLVuw7EM1ROWbswW6pr7eYVhtIHJHNCFoGicvT9tfO9kSnF1cfrK0QB03xWqbpaaFsZc7Lm4t98TzRg7kyPoSgrFgQwmZ6bt/mt7oKlay+HzOnZ6L1oy0QZFTd7IrcfopuuJa8kcYb0RkOviS5xcimjy3Tiewi7FDsecSbfLl8Q4Emd2iu17zK4+kwZLzznuPTot+szcvkLu5n7K7FTfcy2Ls5C+g+nNWuxeXnEmkRBHvbKLmwSZyb528HZnE1gbEknaeos+FZBkXkZ5CwtEgYfpimn2X0mpC/32i8k/J07II2aEHA7d7tVUYf0ghQeBtFsYmkhBxUW1WQSLfN4a+lXZuXKNafqpPlPQCpBPzL6SDyYkIbNawS233jqOTp0Xjt4eChqB03UBrdY0YQZU/LhDeHy50QBhH3WwgRZBtwrrNLu9GJ9qlvT/O41qvZ669mrCYPLr7N6O738Y8xHdeHj8yYzzWWqT7q91bz5hH8PhBeDbOBa+Q9+/IDHK0j5alyLuwFuFCjR02axjXBaU="
  secret-access-key:
    secure: "HS9vs2KeBNoXzJ0rS65nW0XGr1CaktJpZs51gL4kb5MHNfuqDSFftxkMQqBe4bKp1ToS3RN8jSkr4SigcTSW0VQyEZiV1x53uFUW1jIa0OotgUkfkYKLxKv8GGp4sk+17OT+sHlyY/bZOUAFjbIX4e5fI6l9MXCE2IZ/2UAoqBOsZrEtukPL7NuRpEL2AgRpO+tNM23yUmXuBFDRfu+RQ7icFPkyIRNZO9i0MwkoV9VBDj7cR1jm1dBNrZqjQFzO2swPrL+dktpYwFZiKGGQW2td563y/JidUrOnuroAIHtC4poY3F9a0Pkut+b0kYiv9S0VBHYH2Z0rlHV2uieYB9RlqCEdxVW+NVoSvrPHXnDG1YEJZM1+6a6T0nr0rv+9W7JEKvUTTmZS1WNUmvUK5PoJO+4CynqcPQUMaQ3b8kIQWSBVj7yLnKlSApQpm/exyJUTCDWJBhuUiHAsCFG8QR84gIbyto50k298EkpunfThnj2NpQk8NHIDnfpwdshjWXhvf/1eTBmNd10GZoSTwAI+g01dhdQ8SF3dDDY0sdWCmzxNvss9gZ6C+9TABzfUbbRF9PHixbu4I616ihIQ+saO5Su6zk30A5rNSnaKlX/CBeld/S418RNU8lEMGetIdgMTx7PGhfcEBCr2iM2iItE4X6xEWTtSHAN5UAfD9jI="
  region: ap-southeast-1
  app: somleng
  env: somleng-production
  bucket_name: pin-somlengci
  on:
    repo: dwilkie/somleng
    branch: somleng.ews1294.info
addons:
  code_climate:
    repo_token:
      secure: "yyNen+T2CrdWZIxHS24WyQlKBqcC1JEnim2XuIlLwHwxRVTzecf5BVrK3PRFUHI2N9KaLDO7FH9yagJnHxlgTZdiVk83A71Pr9kSCZ5GKjfXMiWJzcXv+jSzBoAKVtx4N6FlHulTzOOvCjtct1hJwSgpH/8z8AOTRdjWk3So/8K1K/q9eL/ZswqVc2DVK/vgDbzhvwGSQNDOKAsvLvEH87nf4Wmz7S4g3ahuV8bzREF+PqTOtHm65vuABAmEF3cbuu/2tp/w3k2h0YHL5vDcmIqhQKlExD77ESLz9UOEvwPQgrazmarW3FFa8Ny7yijJINb8OPxNN/t1yCqlmGCZs/Em+cicegm+iQogrNKK6mHS/YgTOkxORiF2MJ4+y6NnA79WN1FPAE+hTp7kazcIl0dZjc0StTBGnypIVYZpGI4mUWC1SiwvPRa3K91TGSK8oJD8poUrn8/Hy9BoVpto+HpFyIaJF379CoHvzLrdhnFpawXPMqtsPn46Az9C6lJGe9BVifF4TrHm8ARpgg1N3ZR1GN1ajCnGyCDaFPQo/tTkGHDCiCP8KG0LUNQQBRIruxr1m+CqeYeBD/nHwrP3t7ozEF6RJvlyosGJo0aoindtDFUYmGYPrMk4UDGGGMgE9CESZdD9YbrYo3SkCtFJhmJ0QDdzRAiHLmcXTdPNHtQ="
after_success:
- bundle exec codeclimate-test-reporter
